### ISSUE TITLE
Cleaning Data & Automating Tasks -- Session 2

### ISSUE THREAD

**Issue by nick-ulle** [ucdavisdatalab/workshop_intermediate_r#4]
[Topic schedule](https://docs.google.com/spreadsheets/d/1cldCE7Pmx6PxzwQnvZlztJWG1YP1i5O03uzY61v7i5I/edit#gid=0)

This session is tentatively titled "Automating Tasks".

TODO:
* [x] Add learning goals
* [x] Write an introduction
* [x] Import content from R Basics appendix ("Loops")
* [ ] Organize and edit imported content for flow
* [ ] Write case study for using loops (e.g., reading multiple Excel files in the style of [this assignment][hw]. @wes-brooks had a data set from D-RUG, or else use the USDA data)
* [ ] Develop new content. Possibly an introduction to [purrr][] (compare/contrast with `*apply` functions) and functional programming approaches to automation
* [ ] Prepare/post data sets for students

[hw]: https://github.com/nick-ulle/2017-sta141b/blob/master/assignments/assignment3/assignment3-solutions.ipynb
[purrr]: https://purrr.tidyverse.org/index.html

**Comment by wes-brooks** [comment]
[This reader by Liza Wood](https://d-rug.github.io/realworld_functions_iteration/putting-it-together.html) is a good example of iterating an operation on all the files in a directory. She rewrote it to use `apply`s instead of looping (based on advice from your R-basics reader), but that could be changed.
