### ISSUE TITLE
Cannot knit current repo without data files

### ISSUE THREAD

**Issue by nistara** [ucdavisdatalab/workshop_intermediate_r#9]
Thanks for this helpful reader! I couldn't run knit.R successfully without downloading some data files that are currently not in the data folder (fruit/some ocean data/cost1222.txt). I'm curious if there's a way that you've been knitting that circumvents the requirement for these files, or maybe I missed something? Thanks!

**Comment by nick-ulle** [comment]
We typically don't store data in git repos unless it's very small, which is why the data is missing.

All of the datasets we used are (hopefully) linked to in the reader, so if you download them and put them in a `data/` directory at the top level of the repo, then it should be possible to build the reader yourself.

We need a better/automated way to handle this problem, since it affects many of our readers, but none of us have had time to set one up yet.

**Comment by nistara** [comment]
Thanks for clarifying, Nick - all the datasets were in the reader and nicely noted there, so I did download them and build the reader. I was originally curious if I missed anything with the workflow since there were some data files in the repo already. Thanks again!
